### ISSUE TITLE
Production catalog being created - I don't want one.

### ISSUE THREAD

**Issue by grahampugh** [pebbleit/munki-trello#1]
Hi Graham,
Just set up this excellent tool and getting to grips with it.
My 'production' catalog is called 'standard', so I'm using the following Docker run:

docker run --rm \
  -v /var/www/html/munki_repo:/munki_repo \
  -e DOCKER_TRELLO_KEY=MYKEY \
  -e DOCKER_TRELLO_TOKEN=MYTOKEN \
  -e DOCKER_TRELLO_BOARDID=MYBOARDID \
  -e DOCKER_TRELLO_TO_PROD_LIST="To Standard" \
  -e DOCKER_TRELLO_SUFFIX=standard \
  pebbleit/munki-trello

The Suffix flag creates a Trello list correctly, but the items are actually moved into a catalog called 'production', which in my repo doesn't exist (until this process creates it). The script needs to allow the 'production' catalog variable to reflect the Suffix flag value. Line 240 should do it. 

Looking at the script, I think the same is true for the development and testing lists, if they happen to be called something else.

Better still, separate keys like DOCKER_MUNKI_DEV_CATALOG, DOCKER_MUNKI_TEST_CATALOG, DOCKER_MUNKI_PROD_CATALOG would allow the displayed lists on trello and the actual catalog names to be different (e.g. have a capital letter).

Another minor thing, when makecatalogs is run at the end, a warning: "WARNING: FoundationPlist is not available, using plistlib instead." Not sure how much this matters - looking at your Sal Docker article on AFP458, I'm guessing it's not important.

**Comment by henrydobson** [comment]
Hi Graham, I'm just doing some house keeping. This repo is not being actively maintained here right now. Please look to https://github.com/grahamgilbert/munki-trello

Thanks, H
