### ISSUE TITLE
Documents don't mention python dependancy

### ISSUE THREAD

**Issue by bandwith** [pebbleit/munki-trello#3]
``` python
python munki-trello.py 
Traceback (most recent call last):
  File "munki-trello.py", line 2, in <module>
    import trello as trellomodule
ImportError: No module named trello
```

Any best practices with regards on how to add this module for 10.10.2?

**Comment by grahamgilbert** [comment]
Shows how much I deploy this on OSX! 

sudo easy_install trello 

Should work (can't test, I'm mobile)

**Comment by grahamgilbert** [comment]
Did you have any success with that @bandwith?

**Comment by bandwith** [comment]
Yes. It worked first time, then I left for the pub.

@grahamgilbert got me thinking, would AutoPkg itself run natively on RHEL7

**Comment by grahamgilbert** [comment]
No, autopkg requires OS X.
